[ISSUE #2898] Resolve rocketmq-example project failed during checkstyle execution.
apache/rocketmq pull request #2899
Opened 2021-05-17 07:27 UTC by zhangjidi2016

**Make sure set the target branch to `develop`**

## What is the purpose of the change

#2898

2021-05-18 02:04 UTC, francisoliverlee requested changes
as i build with lastest codes, all is fine. 
check your local IDE config

2021-05-18 06:38 UTC, zhangjidi2016 commented
> as i build with lastest codes, all is fine.
> check your local IDE config

2021-05-18 06:48 UTC, zhangjidi2016 commented
When I use the CheckStyle plugin to check the code following the checkstyle.xml specification in RocketMQ, the check does not pass
![image](https://user-images.githubusercontent.com/18254437/118603880-12764000-b7e7-11eb-96e9-464c092ced44.png)
![image](https://user-images.githubusercontent.com/18254437/118603990-32a5ff00-b7e7-11eb-9dd1-41358d0915c2.png)

2021-05-19 01:58 UTC, vongosling commented
Yes, you are correct. Note that we have bound checkstyle to verify the phase now. If bound to the validate phase, it would check the code prior to compiling the code. If the code is invalid, the parsing errors reported by checkstyle may be different than what would be expected from the javac compiler. However, it's guaranteed to run. But for verify phase which would run much later (and allow the javac compiler to flag invalid code prior to checkstyle). However, if developers generally just use "mvn test" prior to pushing changes, checkstyle would not run as verify occurs after the test phase.

2021-05-19 02:00 UTC, merged