[ISSUE 2072] Implement DefaultMQAdminExt::examineSubscriptionGroupConfig method
apache/rocketmq pull request #3354
Opened 2021-09-14 12:03 UTC by haozhijie9527

**Make sure set the target branch to `develop`**

## What is the purpose of the change

implement examineSubscriptionGroupConfig function on the client, avoid problems that may occur when the broker and client versions are inconsistent

2021-09-16 12:19 UTC, haozhijie9527 commented
#3355

2021-09-16 12:27 UTC, areyouok approved these changes

2021-09-17 02:37 UTC, francisoliverlee requested changes
there would be not that OK reading ALL consumer group configs but for one.

2021-09-18 03:25 UTC, haozhijie9527 commented
> there would be not that OK reading ALL consumer group configs but for one.

All right, I will close this pr, and I think pr #3039 has same problem

2021-09-18 03:25 UTC, closed without merging