[ISSUE #3654] Polish travis.yml to run integration tests
apache/rocketmq pull request #3655
Opened 2021-12-15 14:52 UTC by RongtongJin

**Make sure set the target branch to `develop`**

## What is the purpose of the change

Polish travis.yml to run integration tests
#3654

## Brief changelog

1.Make travis to run integration tests
2.Fix running testSynSendNullMessage failed

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily. Notice, `it would be helpful if you could finish the following 5 checklist(the last one is not necessary)before request the community to review your PR`.

- [x] Make sure there is a [Github issue](https://github.com/apache/rocketmq/issues) filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue. 
- [x] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Write necessary unit-test(over 80% coverage) to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/apache/rocketmq/tree/master/test).
- [x] Run `mvn -B clean apache-rat:check findbugs:findbugs checkstyle:checkstyle` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.
- [ ] If this contribution is large, please file an [Apache Individual Contributor License Agreement](http://www.apache.org/licenses/#clas).

2021-12-16 03:02 UTC, duhenglucky approved these changes

2021-12-16 06:07 UTC, odbozhou approved these changes

2021-12-16 08:56 UTC, guyinyou approved these changes

2021-12-17 01:05 UTC, vongosling requested changes

2021-12-17 01:05 UTC, vongosling commented on .travis.yml
> +  - travis_retry mvn -B install jacoco:report coveralls:report
ITTest is designed to execute after we run successfully. We have two tasks when building, after success is a heavy operation. If we remove it, we must opt for the core ITTest case. Meanwhile, The queuing problem is very serious and will be exacerbated if you mix long-running tasks in a light task. Our CI/CD system design has been carefully considered. When optimizing the CI/CD system, we should consider all aspects.

2021-12-17 01:53 UTC, merged