123monkey remove else
apache/rocketmq pull request #4674
Opened 2022-07-23 12:45 UTC by 123monkey

**Make sure set the target branch to `develop`**

## What is the purpose of the change

remove redundant else

## Brief changelog

remove redundant else

## Verifying this change

remove redundant else

Follow this checklist to help us incorporate your contribution quickly and easily. Notice, `it would be helpful if you could finish the following 5 checklist(the last one is not necessary)before request the community to review your PR`.

- [x] Make sure there is a [Github issue](https://github.com/apache/rocketmq/issues) filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue. 
- [x] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Write necessary unit-test(over 80% coverage) to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/apache/rocketmq/tree/master/test).
- [x] Run `mvn -B clean apache-rat:check findbugs:findbugs checkstyle:checkstyle` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.
- [ ] If this contribution is large, please file an [Apache Individual Contributor License Agreement](http://www.apache.org/licenses/#clas).

2022-07-24 11:17 UTC, Oliverwqcwrw approved these changes

2022-07-29 05:20 UTC, aaron-ai requested changes

2022-07-29 05:20 UTC, aaron-ai commented on client/src/main/java/org/apache/rocketmq/client/impl/producer/TopicPublishInfo.java
> +                pos = 0;
```suggestion
            if (pos < 0) {
                pos = 0;
            }
```

2022-08-10 02:45 UTC, guyinyou approved these changes
lgtm

2022-08-23 02:17 UTC, tsunghanjacktsai submitted a review, later dismissed

2022-09-01 02:04 UTC, lizhanhui commented
@123monkey Can you please rebase on top of the latest `develop` branch?

2022-09-02 02:40 UTC, ni-ze approved these changes
LGTM

2022-09-06 02:32 UTC, aaron-ai approved these changes

2022-09-08 02:55 UTC, tsunghanjacktsai approved these changes

2022-09-14 00:57 UTC, Oliverwqcwrw approved these changes

2022-09-14 01:58 UTC, caigy approved these changes

2022-09-19 09:29 UTC, guyinyou approved these changes

2023-09-24 00:07 UTC, closed without merging