Update deploy_guide.md
apache/rocketmq pull request #5099
Opened 2022-09-16 06:56 UTC by lizhanhui

**Make sure set the target branch to `develop`**

## What is the purpose of the change

XXXXX

## Brief changelog

XX

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily. Notice, `it would be helpful if you could finish the following 5 checklist(the last one is not necessary)before request the community to review your PR`.

- [x] Make sure there is a [Github issue](https://github.com/apache/rocketmq/issues) filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue. 
- [x] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Write necessary unit-test(over 80% coverage) to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/apache/rocketmq/tree/master/test).
- [x] Run `mvn -B clean apache-rat:check findbugs:findbugs checkstyle:checkstyle` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.
- [ ] If this contribution is large, please file an [Apache Individual Contributor License Agreement](http://www.apache.org/licenses/#clas).

2022-09-17 12:37 UTC, Oliverwqcwrw approved these changes, later dismissed

2022-09-18 03:22 UTC, aaron-ai requested changes

2022-09-18 03:22 UTC, aaron-ai commented on docs/en/proxy/deploy_guide.md
>  ## `Local` mode
```suggestion
## `Local` Mode
```

2022-09-19 01:36 UTC, Oliverwqcwrw requested changes

2022-09-19 01:36 UTC, Oliverwqcwrw commented on docs/en/proxy/deploy_guide.md
> +The previous command will launch the `Proxy`, with `Broker` in the same process. It asssumes `Namesrv` nodes are running at the address specified by `nameSrvAddr`.
```suggestion
The previous command will launch the `Proxy`, with `Broker` in the same process. It assumes `Namesrv` nodes are running at the address specified by `nameSrvAddr`.
```

2022-09-19 05:16 UTC, aaron-ai approved these changes

2022-09-19 06:10 UTC, merged