[ISSUE #5847] Fix wake up in NotificationProcessor
apache/rocketmq pull request #5848
Opened 2023-01-10 08:18 UTC by drpmma

## What is the purpose of the change

close #5847

## Brief changelog

Fix wake up in NotificationProcessor

2023-01-10 09:34 UTC, lizhimins requested changes

2023-01-10 09:34 UTC, lizhimins commented on broker/src/main/java/org/apache/rocketmq/broker/processor/NotificationProcessor.java
> +        // if it has message, fetch retry again
not has message?

2023-01-11 02:19 UTC, caigy reviewed
Could you provide more explanation about the change?

2023-01-11 06:15 UTC, lizhimins approved these changes

2023-01-11 08:09 UTC, merged