Use static subscription to calculate consumer lag and latency
apache/rocketmq pull request #6207
Opened 2023-02-28 07:47 UTC by drpmma

close #6206

2023-03-03 06:09 UTC, ShadowySpirits requested changes

2023-03-03 12:39 UTC, drpmma commented on remoting/src/main/java/org/apache/rocketmq/remoting/protocol/subscription/SubscriptionGroupConfig.java
> +    public Set<SimpleSubscriptionData> getSubscriptionDataSet() {
Because it's possible that there's more that one SimpleSubscriptionData for a topic.

2023-03-06 11:12 UTC, lizhimins approved these changes

2023-03-08 07:18 UTC, aaron-ai approved these changes

2023-03-08 07:47 UTC, merged