[ISSUE #6321] optimize yaml parse code
apache/rocketmq pull request #6322
Opened 2023-03-12 08:05 UTC by yuz10

**Make sure set the target branch to `develop`**

## What is the purpose of the change

fix #6321  

## Brief changelog

XX

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily. Notice, `it would be helpful if you could finish the following 5 checklist(the last one is not necessary)before request the community to review your PR`.

- [x] Make sure there is a [Github issue](https://github.com/apache/rocketmq/issues) filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue. 
- [x] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Write necessary unit-test(over 80% coverage) to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/apache/rocketmq/tree/master/test).
- [x] Run `mvn -B clean apache-rat:check findbugs:findbugs checkstyle:checkstyle` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.
- [ ] If this contribution is large, please file an [Apache Individual Contributor License Agreement](http://www.apache.org/licenses/#clas).

2023-03-14 01:50 UTC, ni-ze approved these changes
LGTM~

2023-03-14 05:38 UTC, caigy requested changes

2023-03-15 01:56 UTC, caigy approved these changes
LGTM

2023-03-15 02:31 UTC, caigy commented
@yuz10 Pls fix spotbug error:
```sh
[INFO] --- spotbugs-maven-plugin:4.2.2:check (check) @ rocketmq-acl ---
[INFO] BugInstance size is 1
[INFO] Error size is 0
[INFO] Total bugs: 1
Error:  High: Class org.apache.rocketmq.acl.plain.PlainAccessData defines non-transient non-serializable instance field accounts [org.apache.rocketmq.acl.plain.PlainAccessData] In PlainAccessData.java SE_BAD_FIELD
```

2023-03-21 02:14 UTC, caigy approved these changes

2023-03-28 02:40 UTC, merged