[ISSUE #6358]Add chinese docs about persistent-unique-broker-id
apache/rocketmq pull request #6359
Opened 2023-03-15 17:50 UTC by TheR1sing3un

**Make sure set the target branch to `develop`**

## What is the purpose of the change

1. add chinese docs about persistent-unique-broker-id
closes #6358 

## Brief changelog

XX

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily. Notice, `it would be helpful if you could finish the following 5 checklist(the last one is not necessary)before request the community to review your PR`.

- [x] Make sure there is a [Github issue](https://github.com/apache/rocketmq/issues) filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue. 
- [x] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Write necessary unit-test(over 80% coverage) to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/apache/rocketmq/tree/master/test).
- [x] Run `mvn -B clean apache-rat:check findbugs:findbugs checkstyle:checkstyle` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.
- [ ] If this contribution is large, please file an [Apache Individual Contributor License Agreement](http://www.apache.org/licenses/#clas).

2023-03-15 23:56 UTC, RongtongJin commented on docs/cn/controller/persistent_unique_broker_id.md
> +sh bin/mqadmin getControllerMetaData -a localhost:9878
测试相关内容去掉吧

2023-03-16 01:49 UTC, mxsm requested changes
@TheR1sing3un  文档的结构标题排版需要在处理一下，以及后面的这个图片需要重新整理一下。看起来更加正式一点

2023-03-16 01:49 UTC, mxsm commented on docs/cn/controller/persistent_unique_broker_id.md
> +Broker拿到`NextBrokerId`之后，创建一个临时文件`.broker.meta.temp`，里面记录了`NextBrokerId`(也就是期望应用的`BrokerId`)，以及自己生成一个`RegisterCode`(用于之后的身份校验)也持久化到临时文件中。
需要删除2.2

2023-03-16 01:49 UTC, mxsm commented on docs/cn/image/controller/persistent_unique_broker_id/normal_restart.png
这个图能否重新处理一下

2023-03-16 01:49 UTC, mxsm commented on docs/cn/image/controller/persistent_unique_broker_id/test_1.png
这个图是否可以重新截图整理

2023-03-16 01:49 UTC, mxsm commented on docs/cn/image/controller/persistent_unique_broker_id/test_10.png
这个图是否可以重新截图整理

2023-03-16 01:49 UTC, mxsm commented on docs/cn/image/controller/persistent_unique_broker_id/test_12.png
这个图是否可以重新截图整理

2023-03-16 01:49 UTC, mxsm commented on docs/cn/image/controller/persistent_unique_broker_id/test_13.png
这个图是否可以重新截图整理

2023-03-16 01:49 UTC, mxsm commented on docs/cn/image/controller/persistent_unique_broker_id/test_14.png
这个图是否可以重新截图整理

2023-03-16 03:40 UTC, RongtongJin approved these changes

2023-03-16 06:12 UTC, mxsm approved these changes
LGTM~

2023-03-16 07:17 UTC, merged