1. optimize registerProducer design
apache/rocketmq pull request #6832
Opened 2023-05-29 13:50 UTC by sherlock-lin

### Which Issue(s) This PR Fixes

Fixes #issue_id

### Brief Description

I try optimize ProducerManager registerProducer design and I think the previous code was redundant

### How Did You Test This Change?

I verify through unit testing

![image](https://github.com/apache/rocketmq/assets/19645523/6db3ee1c-570f-4cce-97c7-b951d477853d)

2023-05-30 15:54 UTC, mxsm reviewed
Hi @sherlock-lin  Please link this PR to target ISSUE

2023-06-01 02:13 UTC, sherlock-lin commented
> Hi @sherlock-lin Please link this PR to target ISSUE



> Hi @sherlock-lin Please link this PR to target ISSUE

2023-06-01 02:16 UTC, sherlock-lin commented
> Hi @sherlock-lin Please link this PR to target ISSUE

Hi @mxsm I have linked  target ISSUE

2023-06-02 07:39 UTC, ferrirW approved these changes

2023-06-05 02:48 UTC, drpmma requested changes

2023-06-05 02:48 UTC, drpmma commented on broker/src/main/java/org/apache/rocketmq/broker/client/ProducerManager.java
>          ConcurrentHashMap<Channel, ClientChannelInfo> channelTable = this.groupChannelTable.get(group);
Why not use the return value of putIfAbsent?

2023-06-05 02:48 UTC, drpmma commented on broker/src/main/java/org/apache/rocketmq/broker/client/ProducerManager.java
> +        ClientChannelInfo clientChannelInfoFound = channelTable.putIfAbsent(clientChannelInfo.getChannel(), clientChannelInfo);
It's recommended to use computeIfAbsent rather than if else.

2024-01-26 11:45 UTC, sherlock-lin reviewed
submit

2025-01-30 00:09 UTC, closed without merging