[ISSUE #7231] Fix: proxy client language error
apache/rocketmq pull request #7200
Opened 2023-08-17 03:22 UTC by weihubeats

https://github.com/apache/rocketmq/issues/7231

The client actually uses go, and there is a bug in the language setting here.

2023-08-18 03:38 UTC, weihubeats commented
@xdkxlk Can you help me with this pr?

2023-08-21 07:33 UTC, joeCarf reviewed
there are tests failures and plz give more information about this bug so I can help to review :)

2023-08-21 08:57 UTC, weihubeats commented
@joeCarf All ci checks have now been cleared.

2023-08-21 09:43 UTC, joeCarf commented on proxy/src/main/java/org/apache/rocketmq/proxy/service/message/LocalRemotingCommand.java
> +
redundant line

2023-08-21 09:43 UTC, joeCarf commented on remoting/src/main/java/org/apache/rocketmq/remoting/protocol/LanguageCode.java
> +
redundant line

2023-08-21 09:43 UTC, joeCarf commented on remoting/src/main/java/org/apache/rocketmq/remoting/protocol/LanguageCode.java
> +
BTW, I think the pr title can be named like [ISSUE #xxx] Fix: xxxx

2023-08-21 09:55 UTC, weihubeats commented
done

2023-08-21 09:56 UTC, joeCarf approved these changes
LGTM

2023-08-22 10:56 UTC, drpmma commented
The [issue](https://github.com/apache/rocketmq/issues/7199) says that there is am NPE. But I don't see a relationship between the issue and this pr. 

Could you please explain it?


```text
java.lang.NullPointerException: null
at org.apache.rocketmq.proxy.grpc.v2.channel.GrpcClientChannel.processGetConsumerRunningInfo(GrpcClientChannel.java:213)
at org.apache.rocketmq.proxy.service.relay.ProxyChannel.writeAndFlush(ProxyChannel.java:97)
at org.apache.rocketmq.remoting.netty.NettyRemotingAbstract.invokeSyncImpl(NettyRemotingAbstract.java:476)
at org.apache.rocketmq.remoting.netty.NettyRemotingServer.invokeSync(NettyRemotingServer.java:438)
at org.apache.rocketmq.broker.client.net.Broker2Client.callClient(Broker2Client.java:80)
at org.apache.rocketmq.broker.processor.AdminBrokerProcessor.callConsumer(AdminBrokerProcessor.java:2347)
at org.apache.rocketmq.broker.processor.AdminBrokerProcessor.getConsumerRunningInfo(AdminBrokerProcessor.java:1979)
at org.apache.rocketmq.broker.processor.AdminBrokerProcessor.processRequest(AdminBrokerProcessor.java:278)
at org.apache.rocketmq.remoting.netty.NettyRemotingAbstract.lambda$buildProcessRequestHandler$1(NettyRemotingAbstract.java:312)
at org.apache.rocketmq.remoting.netty.RequestTask.run(RequestTask.java:80)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:750)
```

https://github.com/apache/rocketmq/blob/cc16a1b51216e1e80c22011b8b01e060bb4af8b3/proxy/src/main/java/org/apache/rocketmq/proxy/grpc/v2/channel/GrpcClientChannel.java#L213

2023-08-22 11:19 UTC, weihubeats commented
There are two problems with this issues, one is null and the other is a language code problem that I can split into two issues

2023-08-22 11:27 UTC, weihubeats commented
@drpmma I've changed issues, please help to relook at it

2023-08-23 02:13 UTC, drpmma requested changes

2023-08-23 02:13 UTC, drpmma commented on proxy/src/main/java/org/apache/rocketmq/proxy/service/message/LocalRemotingCommand.java
> +    public static LocalRemotingCommand createRequestCommand(int code, CommandCustomHeader customHeader, ProxyContext ctx) {
It's better to pass language rather than proxyContext into the constructor of LocalRemotingCommand.

2023-08-23 02:43 UTC, drpmma approved these changes
LGTM

2023-08-25 03:22 UTC, weihubeats commented
@drpmma Can this pr be merged?

2023-09-14 03:07 UTC, RongtongJin approved these changes

2023-09-19 02:38 UTC, weihubeats commented
Is this pr ready for merge, and are there any other issues that need to be dealt with?

2023-10-18 11:33 UTC, RongtongJin commented
@weihubeats How about merging lastest code to trigger CI again？

2023-10-18 12:37 UTC, weihubeats commented
@RongtongJin I merge the latest dev bis triggered ci, but a few cid still failed, I feel that this should not be the result of this modification, this test these failed use cases can be successful!

2023-10-19 01:45 UTC, RongtongJin commented
> @RongtongJin I merge the latest dev bis triggered ci, but a few cid still failed, I feel that this should not be the result of this modification, this test these failed use cases can be successful!

I will rerun.

2023-10-19 11:06 UTC, weihubeats commented
Maybe this pr can be merged now. @RongtongJin

2023-10-20 06:49 UTC, merged