[ISSUE #8055]remove unnecessary math.abs() method
apache/rocketmq pull request #8056
Opened 2024-04-23 15:58 UTC by Willhow-Gao

### remove unnecessary math.abs() method in TopicPublishInfo#selectOneMessageQueue

Fixes #8055

### remove unnecessary math.abs() method in TopicPublishInfo#selectOneMessageQueue

### How Did You Test This Change?
In the ThreadLocalIndexTest class, there are already some test that the return value of the incrementAndGet method must be a positive number.

2024-04-23 16:00 UTC, MR-gwh commented
Fix #8055

2024-04-24 09:31 UTC, humkum approved these changes

2024-04-29 10:17 UTC, lizhimins requested changes

2024-04-29 10:17 UTC, lizhimins commented on client/src/main/java/org/apache/rocketmq/client/impl/producer/TopicPublishInfo.java
> +                int index = sendQueue.incrementAndGet() % messageQueueList.size();
这是个 thread local int，用完会再从 0 开始，不能去掉吧

2024-04-29 15:40 UTC, Willhow-Gao commented on client/src/main/java/org/apache/rocketmq/client/impl/producer/TopicPublishInfo.java
> +                int index = sendQueue.incrementAndGet() % messageQueueList.size();
我理解的是即使是0，做取模操作后的值也会是非负的，不需要再math.abs取绝对值吧

2024-05-06 16:06 UTC, Willhow-Gao commented on client/src/main/java/org/apache/rocketmq/client/impl/producer/TopicPublishInfo.java
> +                int index = sendQueue.incrementAndGet() % messageQueueList.size();
> 这是一个线程local int，用完会再从0开始，不能去掉吧
在同一个类里，也看到了去掉math.abs的用法，应该是确定可以去掉吧，不然下面的方法就会出bug了
<img width="547" alt="image" src="https://github.com/apache/rocketmq/assets/65004897/f409d145-5c4f-4d8b-9f87-f1ccfda09b98">

2024-05-23 02:33 UTC, Willhow-Gao commented
@lizhimins Please cr again. thx

2025-05-27 00:11 UTC, closed without merging