[ISSUE #8594] Tiered storage shouldn't access remote when it comes to dispatch or query topic whose reserved time is not configured
apache/rocketmq pull request #8595
Opened 2024-08-28 11:55 UTC by bxfjb

### Which Issue(s) This PR Fixes

Fixes #8594 

### Brief Description

### How Did You Test This Change?

2024-08-29 06:21 UTC, lizhimins reviewed
Can you add some test cases? Currently, the coverage rate of hierarchical storage modules is 80-90%

2024-08-29 09:54 UTC, bxfjb commented
> Can you add some test cases? Currently, the coverage rate of hierarchical storage modules is 80-90%
Ofc, I'll add ut later.

2024-08-30 08:01 UTC, bxfjb commented
> Can you add some test cases? Currently, the coverage rate of hierarchical storage modules is 80-90%

done :)

2024-09-05 06:20 UTC, lizhimins approved these changes

2024-09-06 02:24 UTC, lizhimins requested changes
1. 在最初和迭代后的版本中，broker 默认会上传所有非系统 topic 实现数据的完全对齐，这里修改了 dispatch 逻辑，相当于修改了默认行为，会导致保留时间小于 broker 默认保留时间的部分都无法上传
2. 在 @yuz10 的改动中，topic meta 中的 reserve time 是一个可选值，这里没有考虑。
3. 如果要实现 1 的功能，建议使用 topic filter 做扩展就好了

2024-09-09 02:20 UTC, bxfjb commented
> 1. 在最初和迭代后的版本中，broker 默认会上传所有非系统 topic 实现数据的完全对齐，这里修改了 dispatch 逻辑，相当于修改了默认行为，会导致保留时间小于 broker 默认保留时间的部分都无法上传
> 2. 在 @yuz10 的改动中，topic meta 中的 reserve time 是一个可选值，这里没有考虑。
> 3. 如果要实现 1 的功能，建议使用 topic filter 做扩展就好了

明白你的意思了，这个 patch 的初衷是降低冷存的占用空间，但是会破坏冷热数据的完全对齐，可能会导致 static topic 出现问题，我会 close 这个

2024-09-09 02:20 UTC, closed without merging