[ISSUE #8712] Set namesrvAddrChoosed to null if choosed addr is not exist.
apache/rocketmq pull request #8713
Opened 2024-09-19 03:07 UTC by qianye1001

…ient is no longer in use, a new channel connection will be created.

### Which Issue(s) This PR Fixes

Fixes #8712

### Brief Description

### How Did You Test This Change?

2024-09-20 07:53 UTC, fuyou001 requested changes
CR need

2024-09-20 07:54 UTC, fuyou001 requested changes
CR need

2024-09-23 02:15 UTC, fuyou001 approved these changes
LGTM

2024-09-23 03:59 UTC, lizhimins approved these changes

2024-09-23 04:28 UTC, merged